### ISSUE TITLE
Plans

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/wpcli-git#1]
@boonebgorges Are you interested in replacing WP update mechanism with git?

- [ ] Implement is as a community package
- [ ] Use git command only on CLI, Don't call `exec( 'git ...' );` in a webserver
- [ ] Prevent update from wp-admin with a nice message if something is under git control AND wp-cli core commands also
- [ ] How to know what is under git. `.git` file
- [ ] Also implement install functions by hooking WP-CLI commands
- [ ] Reinstall? Rollback?
- [ ] Enable moving `.git` dir outside document root
- [ ] Mention package language should be always en_US
- [ ] Docs: Should be moving wp-content out of ABSPATH

**Comment by boonebgorges** [comment]
I don't know about "replace", but have written commands that tie the two together. See https://github.com/cuny-academic-commons/wp-cli-cac/blob/master/wp-cli-cac.php

**Comment by szepeviktor** [comment]
- Use git command only on CLI, Don't do `exec( 'git ...' );`
- Prevent normal update procedure if something is under git control
- Use WP core hooks

**Comment by szepeviktor** [comment]
> I don't know about "replace"

I am planning to replace core's HTTP-base update mechanism with git, I mean using a remote git repo as https://github.com/WordPress/WordPress

**Comment by boonebgorges** [comment]
Oh, interesting. I'll be curious to see what this looks like.

**Comment by szepeviktor** [comment]
I would hook for example core upgrade and do `git fetch; git checkout v4.7` instead

**Comment by szepeviktor** [comment]
Substituting ZIP handling in core's workflow
```
Updating to version 4.7 (hu_HU)...
U:__construct
    C:upgrade
U:init
U:generic_strings
    C:upgrade_strings
U:fs_connect
    C:check_files
U:create_lock
Using cached file '/home/faluu/.wp-cli/cache/core/wordpress-4.7-hu_HU.zip'...
U:unpack_package
    Frissítés kicsomagolása......
U:release_lock
```

**Comment by szepeviktor** [comment]
Composer is for handling PHP code: https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/wp-install/johnpbloch-composer.json
